apiVersion : v1 #Kubernetes api version
kind : Service #Kubernetes' resource kind we are creating
metadata :
  name : springboot-multithreading-service
spec:
  selector :
    app : springboot-multithreading
  ports :
    - protocol : "TCP"
      port : 8080 # Port on which service is running on k8s cluster
      targetPort : 8080 # The port expose by service
  type: NodePort # type of service